### ISSUE TITLE
Run on visual degree data

### ISSUE THREAD

**Issue by behinger** [MikhailStartsev/deep_em_classifier#3]
can I use this tool on data that are already converted to visual degree?

I saw that the metadata arff entries make a difference in outcome - but hard to counter act the internal function if one doesnt know what exactly it does. In my case I do not have a distance to monitor / pixels, because it is a mobile measurement.

Thanks & Cheers 
Best, Benedikt

**Comment by MikhailStartsev** [comment]
Hi @behinger, and sorry for a late reply, did not notice the issue at first. 
I think the simplest way to achieve what you want is to modify the respective .py file you intend to use (either blstm_model.py or blstm_model_run.py) - since the feature extraction does not alter the units, and just computes speed/direction/acceleration.

Specifically, find the line that defines `keys_to_convert_to_degrees` (e.g. https://github.com/MikhailStartsev/deep_em_classifier/blob/c98eba89f63675c26ebe34b41083c19257034f45/blstm_model.py#L628), and make this list empty instead:
`keys_to_convert_to_degrees = []` 


If you want to maintain working with both degree and pixel data via the same script, one could add a command line argument that would enable/disable to-degree conversion.

Alternatively, if you do not want to modify the code, and would rather modify your data with "fake" distance information to get approximately the same effect, you should look at the PPD calculation here: https://github.com/MikhailStartsev/sp_tool/blob/c663ad303ed3f684d99909a762cb2af396208532/util.py#L83

You want to achieve ppd_x and ppd_y == 1, which means the following metadata requirements:
* width_px == 2 * math.atan(width_mm / (2 * distance_mm)) * 180. / math.pi
* height_px == 2 * math.atan(height_mm / (2 * distance_mm)) * 180. / math.pi

E.g. you could pick width_mm = height_mm = 100.0, distance_mm = 100.0, then width_px = height_px = 53.13
I think it may be more reliable not to convert to degrees at all, though. If you _do_ go through with data modification, I suggest printing the computed ppd value in blstm_model scripts, in the same function you would need to modify to disable the conversion, just to check the correctness of the computation.
