### ISSUE TITLE
Should I use python2.7 for this tool?

### ISSUE THREAD

**Issue by ghost** [MikhailStartsev/deep_em_classifier#4]
seems that I can't install sp_tool in python 3.6

**Comment by MikhailStartsev** [comment]
Hi @minamo816 , sorry for the late reply - yes, the tool was initially written in python 2.7. If you want to use it sooner rather than later, I can suggest using something like [this tool](https://docs.python.org/3/library/2to3.html) to make it python 3 compatible. I expect to update the tool myself as well, but cannot give a precise timeline at the moment.
